server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:backend
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: my-super-secret-key-please-change-it
    expiration: 86400000
